name: Publish Ruby Gem

on:
  workflow_dispatch:

jobs:
  publish-gem:
    defaults:
      run:
        working-directory: Ruby/
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Publish to RubyGems
        run: |
          mkdir -p .gem
          touch .gem/credentials
          chmod 0600 .gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > .gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
